# change the build directory to be within react's scope
project_structure:
  build: client/src/artifacts

# set a custom mnemonic for the development network
networks:
  default: ${DEFAULT_NETWORK}
  development:
    cmd_settings:
      mnemonic: ${WALLET_MNEMONIC}
  kovan:
    cmd_settings:
      mnemonic: ${WALLET_MNEMONIC}
  rinkeby:
    cmd_settings:
      mnemonic: ${WALLET_MNEMONIC}

# enable output of development artifacts to load with react
dev_deployment_artifacts: true

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.0.0

dotenv: .env
