# Change the build directory to be within react's scope
project_structure:
  build: client/src/artifacts

# Set a custom mnemonic for the development network
networks:
  default: ${DEFAULT_NETWORK} # kovan, rinkeby, ...
  development:
    cmd_settings:
      mnemonic: ${WALLET_MNEMONIC}

wallets:
  from_key: ${WALLET_PRIVATE_KEY}

# Enable output of development artifacts to load with react
dev_deployment_artifacts: true

dotenv: .env

dependencies:
  - OpenZeppelin/openzeppelin-contracts@2.5.1
  # - OpenZeppelin/openzeppelin-upgrades@2.7.2
  - OpenZeppelin/openzeppelin-contracts@4.0.0

compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@2.5.1'
      # - '@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.0.0'
      # - '@openzeppelin/upgrades=OpenZeppelin/openzeppelin-upgrades@2.7.2'
