on: [push, pull_request]

name: main workflow

env:
  DEFAULT_NETWORK: ${{ secrets.DEFAULT_NETWORK }}
  WALLET_MNEMONIC: ${{ secrets.WALLET_MNEMONIC }}
  WALLET_PASSWORD: ${{ secrets.WALLET_PASSWORD }}
  WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
  WEB3_INFURA_PROJECT_ID: ${{ secrets.WEB3_INFURA_PROJECT_ID }}
  NODE_OPTIONS: --max_old_space_size=4096
  # ^ increasing available memory for node reduces issues with ganache crashing
  # https://nodejs.org/api/cli.html#cli_max_old_space_size_size_in_megabytes

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Cache Solidity Installations
      uses: actions/cache@v1
      with:
        path: ~/.solcx
        key: ${{ runner.os }}-solcx-cache

    - name: Setup Node.js
      uses: actions/setup-node@v1

    - name: Install Ganache
      run: npm install -g ganache-cli@6.9.1

    - name: Install Solhint
      run: npm install -g solhint

    - name: Setup Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Requirements
      run: pip install -r requirements.txt

    - name: Create .env
      run: |
        touch .env
        echo DEFAULT_NETWORK=$DEFAULT_NETWORK >> .env
        echo WALLET_MNEMONIC=$WALLET_MNEMONIC >> .env
        echo WALLET_PASSWORD=$WALLET_PASSWORD >> .env
        echo WALLET_PRIVATE_KEY=$WALLET_PRIVATE_KEY >> .env
        echo WEB3_INFURA_PROJECT_ID=$WEB3_INFURA_PROJECT_ID >> .env

    - name: Run Tests
      run: brownie test ./tests

    - name: Run Solhint
      run: solhint 'contracts/**/*.sol'
