name: RenPool Workflow

on:
  # We want to trigger these jobs in every branch.
  push:
    # But do not trigger them when only `md` files were modified.
    paths-ignore:
      - '**.md'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - run: touch .env && echo ALCHEMY_KEY=${{ secrets.ALCHEMY_KEY }} >> .env
      - run: yarn test
      - run: yarn test:mainnet

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - run: touch .env && echo ALCHEMY_KEY=${{ secrets.ALCHEMY_KEY }} >> .env
      - run: yarn coverage
      - run: git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
      - run: yarn gh-pages --dist coverage/ --user "Github Workflow Bot <noemail@github.io>"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - run: yarn lint
